version: '3.8'
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
# version: "3.5"
# services:
#   nats:
#     image: nats
#     ports:
#       - "8222:8222"
#     command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
#     networks: ["nats"]
#   nats-1:
#     image: nats
#     command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
#     networks: ["nats"]
#     depends_on: ["nats"]
#   nats-2:
#     image: nats
#     command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
#     networks: ["nats"]
#     depends_on: ["nats"]

# networks:
#   nats:
#     name: nats